/* Pentagonal numbers are generated by the formula,
 * Pn=n(3n−1)/2.
 * 
 * The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
 * However, their difference, 70 − 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their
 * sum and difference are pentagonal and D = |Pk − Pj| is minimised;
 * 
 * what is the value of D?
 * */

public class N044PentagonNumbers {

	public static boolean isPentagonal(int n) {
		double inverse = (1 + Math.sqrt(1 + 24 * n)) / 6;
		return inverse == (int) inverse;
	}

	public static int getPentagonal(int n) {
		return (3 * n * n - n) / 2;
	}

	public static void main(String[] args) {
		double start = System.currentTimeMillis();

		for (int i = 10000; i > 1; --i) {
			for (int j = i - 1; j > 0; j = j - 2) {
				int pi = getPentagonal(i), pj = getPentagonal(j);
				int sum = pi + pj, difference = pi - pj;
				if (isPentagonal(difference) && isPentagonal(sum)) {
					System.out.println(difference);
				}
			}
		}

		double end = System.currentTimeMillis();
		double length = end - start;
		System.out.println("This took " + length + " ms.");
	}
}
